<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

| Term       | Brief description |
|------------|:-----------------|
| Subsetting | Subsetting takes a subset of a list such that the relative order of the elements is preserved |
| Indexing   | Indexing defines a list of keys that may be used to access the elements of an indexed collection |
| Slicing    | Slicing takes a subset by identifying two keys from a set of ordered keys of an indexed collection and defines a list of objects whose keys are between the two identified keys |
| Masking    | Masking selects a subset of a list using a mask, usually generated by a pre-defined criteria |

# Exercise 2

In [8]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_int_array = np_array_2d[:, 0].astype(int)
np_mask = np_int_array % 2 == 1
np_char_array = np_array_2d[np_mask, 1]

print(np_char_array)

['A' 'C' 'E' 'G' 'I']


# Exercise 3

In [ ]:
import numpy as np

np_array = np.array(
[[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

np_criteria_array = np.zeros(np.shape(np_array), dtype=int)

np_above_50_mask = np_array > 50
np_equal_50_mask = np_array == 50
np_below_50_mask = np_array < 50

np_criteria_array[np_above_50_mask] = 1
np_criteria_array[np_equal_50_mask] = 0
np_criteria_array[np_below_50_mask] = -1

print(np_criteria_array)

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
